Update method for checking endpoint protocol
juju/charm-helpers pull request #769
Opened 2023-04-19 12:15 UTC by gnuoy

The `https` method is used to check if an endpoint is expected to be http or https. One of the checks it performs is to examine the the certificates relation. If the relation is present then it looks for the existance of a CA. However the OpenStack charms do not switch to https until a certificate is provided via the certificates relation. This means there can be a disconnect if the certificate provider has provided a CA but has not yet provided the unit specific certificates. If this happens then the payload will still be using http but the `https` method will return True.

This patch updates the `https` method to return False if an unfilled certificate request exists.

https://bugs.launchpad.net/charm-keystone/+bug/2015103

2023-04-19 18:49 UTC, coreycb reviewed
LGTM. Could you add the bug reference to the commit message? 2015103

2023-05-02 09:58 UTC, coreycb submitted a review, later dismissed

2023-05-02 14:22 UTC, wolsen submitted a review, later dismissed

2023-05-03 07:15 UTC, ajkavanagh requested changes
Unfortunately, it looks like a few unit tests are breaking due to the change; it looks like the tests need some additional mocks as the method-under-test eventually calls out to juju primatives.

e.g.

```
                                                                                                                                                                                                                              
======================================================================                                                                                                                                                        
ERROR: tests.contrib.hahelpers.test_cluster_utils.ClusterUtilsTests.test_https_cert_key_incomplete_identity_relation                                                                                                          
----------------------------------------------------------------------                                                                                                                                                        
testtools.testresult.real._StringException: Traceback (most recent call last):                                                                                                                                                
  File "/home/ubuntu/git/github.com/juju/charm-helpers/charmhelpers/core/hookenv.py", line 1180, in inner_translate_exc2                                                                                                      
    return f(*args, **kwargs)                                                                                                                                                                                                 
  File "/home/ubuntu/git/github.com/juju/charm-helpers/charmhelpers/core/hookenv.py", line 1374, in network_get_primary_address                                                                                               
    response = subprocess.check_output(                                                                                                                                                                                       
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output                                                                                                                                                          
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                                                                          
  File "/usr/lib/python3.8/subprocess.py", line 493, in run                                                                                                                                                                   
    with Popen(*popenargs, **kwargs) as process:                                                                                                                                                                              
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__                                                                                                                                                              
    self._execute_child(args, executable, preexec_fn, close_fds,                                                                                                                                                              
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child                                                                                                                                                       
    raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                                              
FileNotFoundError: [Errno 2] No such file or directory: 'network-get' 
```

Unfortunately, the github actions are currently broken due to: https://github.com/juju/charm-helpers/issues/774 so you'll need to run them manually (on say focal), until we get this fixed.

2023-05-03 14:08 UTC, ajkavanagh requested changes
Please see inline test comment; I think a boolean assert should be flipped.

2023-05-03 14:08 UTC, ajkavanagh commented on tests/contrib/hahelpers/test_cluster_utils.py
> +        self.assertTrue(cluster_utils.https())
I think this should be `assertFalse` as the request for local unit is `{}` and that it will return `False` from `https()`.

2023-05-04 07:39 UTC, ajkavanagh commented
I've manually verified that the tox pep8 and py3 targets run on focal and jammy (actually py310 due to nose2 requirement).  This is in lieu of the fix to the CI runners.

2023-05-04 07:40 UTC, merged