Update method for checking endpoint protocol (#769) (#775)
juju/charm-helpers pull request #778
Opened 2023-05-26 18:26 UTC by coreycb

Update method for checking endpoint protocol

The `https` method is used to check if an endpoint is expected to be http or https. One of the checks it performs is to examine the the certificates relation. If the relation is present then it looks for the existance of a CA. However the OpenStack charms do not switch to https until a certificate is provided via the certificates relation. This means there can be a disconnect if the certificate provider has provided a CA but has not yet provided the unit specific certificates. If this happens then the payload will still be using http but the `https` method will return True.

This patch updates the `https` method to return False if an unfilled certificate request exists.

(cherry picked from commit 6064a34627882d1c8acf74644c48d05db67ee3b4)

Co-authored-by: Liam Young <liam.young@canonical.com>
(cherry picked from commit ed01437357921a95f2dedcff1ec50ae68ef46a53)

2023-05-29 19:16 UTC, freyes reviewed
This backport LGTM, although I'm not sure why CI jobs were run here.

2023-05-29 19:17 UTC, freyes approved these changes

2023-05-30 09:52 UTC, ajkavanagh commented
It would be good to link to some reviews that use this functionality on stable/zed charms, please.

2023-06-07 19:08 UTC, freyes requested changes
We should include in this same PR this other patch - https://github.com/juju/charm-helpers/commit/58097330bd15cfd7b539481c55718c6cee8ca124 .

Also this change should be rebased, so the CI can run on this patchset.

2023-06-07 21:05 UTC, freyes reviewed
LGTM. We just need to review/merge the missing fix in stable/antelope first - https://github.com/juju/charm-helpers/pull/799

2023-06-08 13:36 UTC, merged