Support legacy cert requests
juju/charm-helpers pull request #798
Opened 2023-06-06 14:53 UTC by dosaboy

openstack.cert_utils needs to support new and legacy tls cert requests.

Closes-Bug: #2022980

2023-06-06 16:07 UTC, freyes requested changes
I tested this change with ironic-api and it did the trick.

```
$ sudo grep Prox /etc/apache2/sites-enabled/openstack_https_frontend.conf
    ProxyPass / http://localhost:6365/
    ProxyPassReverse / http://localhost:6365/
```

@dosaboy , can you update the commit message to identify where the issue was introduced, why this is needed, etc, also can you add a unit test to make sure we don't introduce regressions down later.

2023-06-07 08:02 UTC, dosaboy commented
commit updated and tests added

2023-06-07 13:37 UTC, freyes approved these changes
LGTM, thanks Ed

2023-06-07 14:12 UTC, freyes approved these changes

2023-06-07 15:40 UTC, javacruft approved these changes

2023-06-07 15:40 UTC, merged