Skip service_resume if already enabled
juju/charm-helpers pull request #882
Opened 2024-03-22 15:51 UTC by dosaboy

Repeatedly calling service_resume for a service that is already enabled can lead to unintended consequences. This adds a check to only resume a serice if it is not enabled.

Related-Bug: #2058505

2024-03-22 20:03 UTC, ajkavanagh requested changes
The unit test(s) should probably be updated/added to to test the new feature.

2024-03-25 14:59 UTC, brianphaley approved these changes
lgtm

2024-03-25 16:00 UTC, arif-ali approved these changes
just tested this through the ovn-chassis charm, and works as expected

2024-03-26 08:08 UTC, fnordahl approved these changes
LGTM, thanks!

2024-03-28 11:15 UTC, ajkavanagh approved these changes

2024-03-28 11:15 UTC, merged